name: Build a POC to deploy Apps using GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
#     https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ubuntu-latest
    steps:
      - name: Check out code base
        uses: actions/checkout@v3
#       https://github.com/marketplace/actions/checkout
      - name: Set up Python version
        uses: actions/setup-python@v3
#       https://github.com/marketplace/actions/setup-python
        with:
          python-version: 3.11
#       - name: Download Artifacts
#         if: ${{ always() }}
#         uses: actions/download-artifact@v3
# #       https://docs.github.com/en/actions/learn-github-actions/expressions
#         with:
#           name: last-build
#           path: ./artifacts/
#       - name: Display downloaded artifacts
#         run: |
#           mkdir -p ./artifacts
#           ls -R ./artifacts
      - name: Run main build
        run: |
            python build.py
      - name: Build artifacts
        run: |
            mkdir -p ./artifacts
            echo $GITHUB_RUN_NUMBER > ./artifacts/latest-version.txt
            echo $GITHUB_SHA > ./artifacts/git-commit.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
#       https://github.com/actions/upload-artifact
        with:
          name: last-build
          path: |
            ./artifacts/latest-version.txt
            ./artifacts/git-commit.txt
  artifacts:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: build
    steps:
      - name: Create Release Assets
        uses: actions/create-release@v1
#       https://github.com/marketplace/actions/create-a-release-in-a-github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Build Assets ${{ github.run_number }}
          body: Latest version number and commit sha
          draft: false
          prerelease: false
