name: Build a POC to deploy Apps using GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
#     https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ubuntu-latest
    steps:
      - name: Check out code base
        uses: actions/checkout@v3
#       https://github.com/marketplace/actions/checkout
      - name: Set up Python version
        uses: actions/setup-python@v3
#       https://github.com/marketplace/actions/setup-python
        with:
          python-version: 3.11
      - name: Download Latest Release Assets
#       https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release
#       https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error
#       https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28#get-a-release-asset
#       https://docs.github.com/en/enterprise-server@3.4/actions/learn-github-actions/variables#default-environment-variables
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_RELEASE_ASSET_URL=$(
            curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | \
            python3 -c "import sys, json; asset = [f for f in json.load(sys.stdin)['assets'] if f['name'] == 'last-build-artifacts.zip']; print(asset[0]['url'])"
          )
          
          curl -L \
          -H "Accept: application/octet-stream" \
          -H "Authorization: Bearer $GITHUB_TOKEN"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "$LATEST_RELEASE_ASSET_URL" \
          --output last-build-artifacts.zip
          
          unzip last-build-artifacts.zip
          ls
      - name: Run main build
        run: |
            python build.py
      - name: Build artifacts
        run: |
            echo $GITHUB_RUN_NUMBER > latest-version.txt
            echo $GITHUB_SHA > git-commit.txt
            zip -r last-build-artifacts-${{ github.run_number }}.zip latest-version.txt git-commit.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
#       https://github.com/actions/upload-artifact
        with:
          name: last-build-artifacts
          path: last-build-artifacts-${{ github.run_number }}.zip
  artifacts:
    runs-on: ubuntu-latest
    permissions:
#   https://stackoverflow.com/questions/67389957/what-permissions-does-github-token-require-for-releases-from-a-github-action
#   https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents
      contents: write
    needs: build
    steps:
      - name: Create Release Assets
        id: create-release-assets
        uses: actions/create-release@v1
#       https://github.com/marketplace/actions/create-a-release-in-a-github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Build Assets ${{ github.run_number }}
          body: Latest version number and commit sha
          draft: false
          prerelease: false
      - name: Download last build artifacts
        uses: actions/download-artifact@v3
#       https://github.com/marketplace/actions/download-a-build-artifact
        with:
          name: last-build-artifacts
      - name: Display downloaded last-build-artifacts
        run: ls
      - name: Upload build artifacts as release assets
        uses: actions/upload-release-asset@v1
#       https://github.com/marketplace/actions/upload-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release-assets.outputs.upload_url }}
          asset_path: last-build-artifacts-${{ github.run_number }}.zip
          asset_name: last-build-artifacts.zip
          asset_content_type: application/zip
          
